
[GetEntity1]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,0}.*?N(.*?)(\||$).*":"\3" 
[Entity1]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity1]Image].png
X         = ([#[&GetEntity1]X] * #TileSize#)
Y         = ([#[&GetEntity1]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity2]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,1}.*?N(.*?)(\||$).*":"\3" 
[Entity2]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity2]Image].png
X         = ([#[&GetEntity2]X] * #TileSize#)
Y         = ([#[&GetEntity2]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity3]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,2}.*?N(.*?)(\||$).*":"\3" 
[Entity3]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity3]Image].png
X         = ([#[&GetEntity3]X] * #TileSize#)
Y         = ([#[&GetEntity3]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity4]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,3}.*?N(.*?)(\||$).*":"\3" 
[Entity4]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity4]Image].png
X         = ([#[&GetEntity4]X] * #TileSize#)
Y         = ([#[&GetEntity4]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity5]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,4}.*?N(.*?)(\||$).*":"\3" 
[Entity5]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity5]Image].png
X         = ([#[&GetEntity5]X] * #TileSize#)
Y         = ([#[&GetEntity5]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity6]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,5}.*?N(.*?)(\||$).*":"\3" 
[Entity6]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity6]Image].png
X         = ([#[&GetEntity6]X] * #TileSize#)
Y         = ([#[&GetEntity6]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity7]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,6}.*?N(.*?)(\||$).*":"\3" 
[Entity7]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity7]Image].png
X         = ([#[&GetEntity7]X] * #TileSize#)
Y         = ([#[&GetEntity7]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity8]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,7}.*?N(.*?)(\||$).*":"\3" 
[Entity8]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity8]Image].png
X         = ([#[&GetEntity8]X] * #TileSize#)
Y         = ([#[&GetEntity8]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity9]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,8}.*?N(.*?)(\||$).*":"\3" 
[Entity9]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity9]Image].png
X         = ([#[&GetEntity9]X] * #TileSize#)
Y         = ([#[&GetEntity9]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity10]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,9}.*?N(.*?)(\||$).*":"\3" 
[Entity10]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity10]Image].png
X         = ([#[&GetEntity10]X] * #TileSize#)
Y         = ([#[&GetEntity10]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity11]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,10}.*?N(.*?)(\||$).*":"\3" 
[Entity11]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity11]Image].png
X         = ([#[&GetEntity11]X] * #TileSize#)
Y         = ([#[&GetEntity11]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity12]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,11}.*?N(.*?)(\||$).*":"\3" 
[Entity12]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity12]Image].png
X         = ([#[&GetEntity12]X] * #TileSize#)
Y         = ([#[&GetEntity12]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity13]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,12}.*?N(.*?)(\||$).*":"\3" 
[Entity13]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity13]Image].png
X         = ([#[&GetEntity13]X] * #TileSize#)
Y         = ([#[&GetEntity13]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity14]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,13}.*?N(.*?)(\||$).*":"\3" 
[Entity14]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity14]Image].png
X         = ([#[&GetEntity14]X] * #TileSize#)
Y         = ([#[&GetEntity14]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity15]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,14}.*?N(.*?)(\||$).*":"\3" 
[Entity15]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity15]Image].png
X         = ([#[&GetEntity15]X] * #TileSize#)
Y         = ([#[&GetEntity15]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity16]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,15}.*?N(.*?)(\||$).*":"\3" 
[Entity16]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity16]Image].png
X         = ([#[&GetEntity16]X] * #TileSize#)
Y         = ([#[&GetEntity16]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity17]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,16}.*?N(.*?)(\||$).*":"\3" 
[Entity17]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity17]Image].png
X         = ([#[&GetEntity17]X] * #TileSize#)
Y         = ([#[&GetEntity17]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity18]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,17}.*?N(.*?)(\||$).*":"\3" 
[Entity18]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity18]Image].png
X         = ([#[&GetEntity18]X] * #TileSize#)
Y         = ([#[&GetEntity18]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity19]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,18}.*?N(.*?)(\||$).*":"\3" 
[Entity19]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity19]Image].png
X         = ([#[&GetEntity19]X] * #TileSize#)
Y         = ([#[&GetEntity19]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity20]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,19}.*?N(.*?)(\||$).*":"\3" 
[Entity20]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity20]Image].png
X         = ([#[&GetEntity20]X] * #TileSize#)
Y         = ([#[&GetEntity20]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity21]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,20}.*?N(.*?)(\||$).*":"\3" 
[Entity21]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity21]Image].png
X         = ([#[&GetEntity21]X] * #TileSize#)
Y         = ([#[&GetEntity21]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity22]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,21}.*?N(.*?)(\||$).*":"\3" 
[Entity22]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity22]Image].png
X         = ([#[&GetEntity22]X] * #TileSize#)
Y         = ([#[&GetEntity22]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity23]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,22}.*?N(.*?)(\||$).*":"\3" 
[Entity23]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity23]Image].png
X         = ([#[&GetEntity23]X] * #TileSize#)
Y         = ([#[&GetEntity23]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity24]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,23}.*?N(.*?)(\||$).*":"\3" 
[Entity24]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity24]Image].png
X         = ([#[&GetEntity24]X] * #TileSize#)
Y         = ([#[&GetEntity24]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity25]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,24}.*?N(.*?)(\||$).*":"\3" 
[Entity25]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity25]Image].png
X         = ([#[&GetEntity25]X] * #TileSize#)
Y         = ([#[&GetEntity25]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity26]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,25}.*?N(.*?)(\||$).*":"\3" 
[Entity26]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity26]Image].png
X         = ([#[&GetEntity26]X] * #TileSize#)
Y         = ([#[&GetEntity26]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity27]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,26}.*?N(.*?)(\||$).*":"\3" 
[Entity27]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity27]Image].png
X         = ([#[&GetEntity27]X] * #TileSize#)
Y         = ([#[&GetEntity27]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity28]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,27}.*?N(.*?)(\||$).*":"\3" 
[Entity28]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity28]Image].png
X         = ([#[&GetEntity28]X] * #TileSize#)
Y         = ([#[&GetEntity28]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity29]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,28}.*?N(.*?)(\||$).*":"\3" 
[Entity29]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity29]Image].png
X         = ([#[&GetEntity29]X] * #TileSize#)
Y         = ([#[&GetEntity29]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity30]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,29}.*?N(.*?)(\||$).*":"\3" 
[Entity30]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity30]Image].png
X         = ([#[&GetEntity30]X] * #TileSize#)
Y         = ([#[&GetEntity30]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity31]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,30}.*?N(.*?)(\||$).*":"\3" 
[Entity31]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity31]Image].png
X         = ([#[&GetEntity31]X] * #TileSize#)
Y         = ([#[&GetEntity31]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity32]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,31}.*?N(.*?)(\||$).*":"\3" 
[Entity32]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity32]Image].png
X         = ([#[&GetEntity32]X] * #TileSize#)
Y         = ([#[&GetEntity32]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity33]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,32}.*?N(.*?)(\||$).*":"\3" 
[Entity33]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity33]Image].png
X         = ([#[&GetEntity33]X] * #TileSize#)
Y         = ([#[&GetEntity33]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity34]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,33}.*?N(.*?)(\||$).*":"\3" 
[Entity34]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity34]Image].png
X         = ([#[&GetEntity34]X] * #TileSize#)
Y         = ([#[&GetEntity34]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity35]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,34}.*?N(.*?)(\||$).*":"\3" 
[Entity35]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity35]Image].png
X         = ([#[&GetEntity35]X] * #TileSize#)
Y         = ([#[&GetEntity35]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity36]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,35}.*?N(.*?)(\||$).*":"\3" 
[Entity36]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity36]Image].png
X         = ([#[&GetEntity36]X] * #TileSize#)
Y         = ([#[&GetEntity36]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity37]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,36}.*?N(.*?)(\||$).*":"\3" 
[Entity37]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity37]Image].png
X         = ([#[&GetEntity37]X] * #TileSize#)
Y         = ([#[&GetEntity37]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity38]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,37}.*?N(.*?)(\||$).*":"\3" 
[Entity38]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity38]Image].png
X         = ([#[&GetEntity38]X] * #TileSize#)
Y         = ([#[&GetEntity38]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity39]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,38}.*?N(.*?)(\||$).*":"\3" 
[Entity39]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity39]Image].png
X         = ([#[&GetEntity39]X] * #TileSize#)
Y         = ([#[&GetEntity39]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity40]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,39}.*?N(.*?)(\||$).*":"\3" 
[Entity40]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity40]Image].png
X         = ([#[&GetEntity40]X] * #TileSize#)
Y         = ([#[&GetEntity40]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity41]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,40}.*?N(.*?)(\||$).*":"\3" 
[Entity41]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity41]Image].png
X         = ([#[&GetEntity41]X] * #TileSize#)
Y         = ([#[&GetEntity41]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity42]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,41}.*?N(.*?)(\||$).*":"\3" 
[Entity42]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity42]Image].png
X         = ([#[&GetEntity42]X] * #TileSize#)
Y         = ([#[&GetEntity42]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity43]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,42}.*?N(.*?)(\||$).*":"\3" 
[Entity43]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity43]Image].png
X         = ([#[&GetEntity43]X] * #TileSize#)
Y         = ([#[&GetEntity43]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity44]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,43}.*?N(.*?)(\||$).*":"\3" 
[Entity44]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity44]Image].png
X         = ([#[&GetEntity44]X] * #TileSize#)
Y         = ([#[&GetEntity44]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity45]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,44}.*?N(.*?)(\||$).*":"\3" 
[Entity45]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity45]Image].png
X         = ([#[&GetEntity45]X] * #TileSize#)
Y         = ([#[&GetEntity45]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity46]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,45}.*?N(.*?)(\||$).*":"\3" 
[Entity46]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity46]Image].png
X         = ([#[&GetEntity46]X] * #TileSize#)
Y         = ([#[&GetEntity46]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity47]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,46}.*?N(.*?)(\||$).*":"\3" 
[Entity47]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity47]Image].png
X         = ([#[&GetEntity47]X] * #TileSize#)
Y         = ([#[&GetEntity47]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity48]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,47}.*?N(.*?)(\||$).*":"\3" 
[Entity48]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity48]Image].png
X         = ([#[&GetEntity48]X] * #TileSize#)
Y         = ([#[&GetEntity48]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity49]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,48}.*?N(.*?)(\||$).*":"\3" 
[Entity49]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity49]Image].png
X         = ([#[&GetEntity49]X] * #TileSize#)
Y         = ([#[&GetEntity49]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity50]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,49}.*?N(.*?)(\||$).*":"\3" 
[Entity50]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity50]Image].png
X         = ([#[&GetEntity50]X] * #TileSize#)
Y         = ([#[&GetEntity50]Y] * #TileSize#)
DynamicVariables = 1

[GetEntity51]
Measure = String
String  = [Entities]
Group   = EntityUpdate
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,50}.*?N(.*?)(\||$).*":"\3" 
[Entity51]
Meter     = Image
Group     = EntityUpdate
ImageName = #@#Games/#Game#/Resources/Sprites/[#[&GetEntity51]Image].png
X         = ([#[&GetEntity51]X] * #TileSize#)
Y         = ([#[&GetEntity51]Y] * #TileSize#)
DynamicVariables = 1
