
[GetObjectLayer1]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,0}(.*?)(\||$).*":"\3" 
[ObjectLayer1]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer1]
DynamicVariables = 1

[GetObjectLayer2]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,1}(.*?)(\||$).*":"\3" 
[ObjectLayer2]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer2]
DynamicVariables = 1

[GetObjectLayer3]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,2}(.*?)(\||$).*":"\3" 
[ObjectLayer3]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer3]
DynamicVariables = 1

[GetObjectLayer4]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,3}(.*?)(\||$).*":"\3" 
[ObjectLayer4]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer4]
DynamicVariables = 1

[GetObjectLayer5]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,4}(.*?)(\||$).*":"\3" 
[ObjectLayer5]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer5]
DynamicVariables = 1

[GetObjectLayer6]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,5}(.*?)(\||$).*":"\3" 
[ObjectLayer6]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer6]
DynamicVariables = 1

[GetObjectLayer7]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,6}(.*?)(\||$).*":"\3" 
[ObjectLayer7]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer7]
DynamicVariables = 1

[GetObjectLayer8]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,7}(.*?)(\||$).*":"\3" 
[ObjectLayer8]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer8]
DynamicVariables = 1

[GetObjectLayer9]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,8}(.*?)(\||$).*":"\3" 
[ObjectLayer9]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer9]
DynamicVariables = 1

[GetObjectLayer10]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,9}(.*?)(\||$).*":"\3" 
[ObjectLayer10]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer10]
DynamicVariables = 1

[GetObjectLayer11]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,10}(.*?)(\||$).*":"\3" 
[ObjectLayer11]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer11]
DynamicVariables = 1

[GetObjectLayer12]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,11}(.*?)(\||$).*":"\3" 
[ObjectLayer12]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer12]
DynamicVariables = 1

[GetObjectLayer13]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,12}(.*?)(\||$).*":"\3" 
[ObjectLayer13]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer13]
DynamicVariables = 1

[GetObjectLayer14]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,13}(.*?)(\||$).*":"\3" 
[ObjectLayer14]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer14]
DynamicVariables = 1

[GetObjectLayer15]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,14}(.*?)(\||$).*":"\3" 
[ObjectLayer15]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer15]
DynamicVariables = 1

[GetObjectLayer16]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,15}(.*?)(\||$).*":"\3" 
[ObjectLayer16]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer16]
DynamicVariables = 1

[GetObjectLayer17]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,16}(.*?)(\||$).*":"\3" 
[ObjectLayer17]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer17]
DynamicVariables = 1

[GetObjectLayer18]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,17}(.*?)(\||$).*":"\3" 
[ObjectLayer18]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer18]
DynamicVariables = 1

[GetObjectLayer19]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,18}(.*?)(\||$).*":"\3" 
[ObjectLayer19]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer19]
DynamicVariables = 1

[GetObjectLayer20]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,19}(.*?)(\||$).*":"\3" 
[ObjectLayer20]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer20]
DynamicVariables = 1

[GetObjectLayer21]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,20}(.*?)(\||$).*":"\3" 
[ObjectLayer21]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer21]
DynamicVariables = 1

[GetObjectLayer22]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,21}(.*?)(\||$).*":"\3" 
[ObjectLayer22]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer22]
DynamicVariables = 1

[GetObjectLayer23]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,22}(.*?)(\||$).*":"\3" 
[ObjectLayer23]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer23]
DynamicVariables = 1

[GetObjectLayer24]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,23}(.*?)(\||$).*":"\3" 
[ObjectLayer24]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer24]
DynamicVariables = 1

[GetObjectLayer25]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,24}(.*?)(\||$).*":"\3" 
[ObjectLayer25]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer25]
DynamicVariables = 1

[GetObjectLayer26]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,25}(.*?)(\||$).*":"\3" 
[ObjectLayer26]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer26]
DynamicVariables = 1

[GetObjectLayer27]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,26}(.*?)(\||$).*":"\3" 
[ObjectLayer27]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer27]
DynamicVariables = 1

[GetObjectLayer28]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,27}(.*?)(\||$).*":"\3" 
[ObjectLayer28]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer28]
DynamicVariables = 1

[GetObjectLayer29]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,28}(.*?)(\||$).*":"\3" 
[ObjectLayer29]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer29]
DynamicVariables = 1

[GetObjectLayer30]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,29}(.*?)(\||$).*":"\3" 
[ObjectLayer30]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer30]
DynamicVariables = 1

[GetObjectLayer31]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,30}(.*?)(\||$).*":"\3" 
[ObjectLayer31]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer31]
DynamicVariables = 1

[GetObjectLayer32]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,31}(.*?)(\||$).*":"\3" 
[ObjectLayer32]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer32]
DynamicVariables = 1

[GetObjectLayer33]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,32}(.*?)(\||$).*":"\3" 
[ObjectLayer33]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer33]
DynamicVariables = 1

[GetObjectLayer34]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,33}(.*?)(\||$).*":"\3" 
[ObjectLayer34]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer34]
DynamicVariables = 1

[GetObjectLayer35]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,34}(.*?)(\||$).*":"\3" 
[ObjectLayer35]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer35]
DynamicVariables = 1

[GetObjectLayer36]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,35}(.*?)(\||$).*":"\3" 
[ObjectLayer36]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer36]
DynamicVariables = 1

[GetObjectLayer37]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,36}(.*?)(\||$).*":"\3" 
[ObjectLayer37]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer37]
DynamicVariables = 1

[GetObjectLayer38]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,37}(.*?)(\||$).*":"\3" 
[ObjectLayer38]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer38]
DynamicVariables = 1

[GetObjectLayer39]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,38}(.*?)(\||$).*":"\3" 
[ObjectLayer39]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer39]
DynamicVariables = 1

[GetObjectLayer40]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,39}(.*?)(\||$).*":"\3" 
[ObjectLayer40]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer40]
DynamicVariables = 1

[GetObjectLayer41]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,40}(.*?)(\||$).*":"\3" 
[ObjectLayer41]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer41]
DynamicVariables = 1

[GetObjectLayer42]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,41}(.*?)(\||$).*":"\3" 
[ObjectLayer42]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer42]
DynamicVariables = 1

[GetObjectLayer43]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,42}(.*?)(\||$).*":"\3" 
[ObjectLayer43]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer43]
DynamicVariables = 1

[GetObjectLayer44]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,43}(.*?)(\||$).*":"\3" 
[ObjectLayer44]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer44]
DynamicVariables = 1

[GetObjectLayer45]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,44}(.*?)(\||$).*":"\3" 
[ObjectLayer45]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer45]
DynamicVariables = 1

[GetObjectLayer46]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,45}(.*?)(\||$).*":"\3" 
[ObjectLayer46]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer46]
DynamicVariables = 1

[GetObjectLayer47]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,46}(.*?)(\||$).*":"\3" 
[ObjectLayer47]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer47]
DynamicVariables = 1

[GetObjectLayer48]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,47}(.*?)(\||$).*":"\3" 
[ObjectLayer48]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer48]
DynamicVariables = 1

[GetObjectLayer49]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,48}(.*?)(\||$).*":"\3" 
[ObjectLayer49]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer49]
DynamicVariables = 1

[GetObjectLayer50]
Measure = String
String  = #ObjectLayers#
Group   = ObjectLayers
DynamicVariables = 1
RegExpSubstitute = 1
Substitute       = "((.*?)\|){0,49}(.*?)(\||$).*":"\3" 
[ObjectLayer50]
Meter     = Image
Group     = ObjectLayers
ImageName = #@#Games/#Game#/Resources/ObjectLayers/#CurrentScreen#/[GetObjectLayer50]
DynamicVariables = 1

